services:
  backend:
    build: .
    container_name: jwt-fastapi-backend
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "8000:8000"
